### ISSUE TITLE
[BUG]: Level 8

### ISSUE THREAD

**Issue by JustMztt** [The-Cove-Dev/wavy-mc#10]
### Discord Details

mztt

### What happened?

![Screenshot 2023-12-10 031621](https://github.com/The-Cove-Dev/wavy-mc/assets/153388826/4c5fd933-7099-469e-9ecf-ab7cc445f2a7)
![Screenshot 2023-12-10 031718](https://github.com/The-Cove-Dev/wavy-mc/assets/153388826/9548da2d-6f18-4346-8184-1e62f8d24bf9)

Level 8 is called level 2 in chat after you redeem it.

### Version

Java Edition (Most PC users)

**Comment by ImSnipper** [comment]
This is now fixed. Thank you.
