### ISSUE TITLE
[BUG]: First level of all the farming quests

### ISSUE THREAD

**Issue by JustMztt** [The-Cove-Dev/wavy-mc#12]
### Discord Details

Mztt

### What happened?

When it comes to bamboo and sugarcane the first level doesnt track the same. it only counts the block you break and not the ones that are above it aswell, but after level 1 it is back to how it should be with counting all the ones that break. 

I then heard from someone else that you can break netherwart from fortresses and it would count for level 1 only (not a big deal but just wanted to note it aswell cause its different)

### Version

Java Edition (Most PC users)

**Comment by itisgriff** [comment]
Fixed.
