### ISSUE TITLE
[Change]: Chat games

### ISSUE THREAD

**Issue by JustMztt** [The-Cove-Dev/wavy-mc#14]
### Discord Details

Mztt

### What happened?

Remove the skin keys from the chat games. they seem like something that is supposed to be a bit rarer than just being quick to click a button sometimes in chat. they also do cost 5 Neptune keys after all. 

### Version

Java Edition (Most PC users)

**Comment by UhhBlaze** [comment]
Skins keys have been removed and replaced with Tropical Keys. 

Additionally, a fix for the rewards will be loaded onto the server this afternoon.
