### ISSUE TITLE
[BUG]: Pig Spawners

### ISSUE THREAD

**Issue by JustMztt** [The-Cove-Dev/wavy-mc#18]
### Discord Details

Mztt

### What happened?

![image](https://github.com/The-Cove-Dev/wavy-mc/assets/153388826/839893bf-48dd-4d54-ba9f-08d52417d499)

Pig spawners are broken

### Version

Java Edition (Most PC users)

**Comment by UhhBlaze** [comment]
@JustMztt Where are these spawners coming from? 

Just tested and are working fine.

**Comment by UhhBlaze** [comment]
Player H20 mentioned they obtained it from Leveling Rewards. 
- Tested leveling reward spawners and they are working as intended as well.
