### ISSUE TITLE
[BUG]: Stacked mobs

### ISSUE THREAD

**Issue by JustMztt** [The-Cove-Dev/wavy-mc#20]
### Discord Details

Mztt

### What happened?

![image](https://github.com/The-Cove-Dev/wavy-mc/assets/153388826/b3c9061a-45a1-434a-b492-808e887467e7)
i every once and awhile find naturally stacked mobs even tho they are not supposed to be stacking

### Version

Java Edition (Most PC users)

**Comment by itisgriff** [comment]
Not sure why this is happening, it is set to only stack mobs from spawners so not sure what that is about.
