### ISSUE TITLE
[BUG]: Some Quest Requirements

### ISSUE THREAD

**Issue by JustMztt** [The-Cove-Dev/wavy-mc#26]
### Discord Details

Mztt

### What happened?

Tropical fish is much too rare to have it be as high as all the others and Redstone doesn't spawn too high in the stone so it makes it hard to find. (there are a lot of complaints about these two quests how they are rn)

Ideas to change them to:

Tropical Fish to 4, 8, 12, 16, 32, 64 

Redstone to 8, 16, 32, 64, 128, 256 

### Version

Java Edition (Most PC users)

**Comment by ImSnipper** [comment]
Done. Tropical Fish, and regular Redstone Ore have been decreased.
