### ISSUE TITLE
[BUG]: Tropical Sword

### ISSUE THREAD

**Issue by JustMztt** [The-Cove-Dev/wavy-mc#8]
### Discord Details

Mztt

### What happened?

Named Tropical Shovel when given

### Version

Java Edition (Most PC users)

**Comment by itisgriff** [comment]
Is this from a crate?

**Comment by JustMztt** [comment]
> Is this from a crate?

yes it is, from the tropical crate

**Comment by itisgriff** [comment]
Fixed.
