### ISSUE TITLE
[BUG]: Skins

### ISSUE THREAD

**Issue by JustMztt** [The-Cove-Dev/wavy-mc#9]
### Discord Details

Mztt

### What happened?

can drop skinned weapons to other players

### Version

Java Edition (Most PC users)

**Comment by JustMztt** [comment]
they might go away after some time from the other player but i cant test it rn

**Comment by itisgriff** [comment]
The skin does eventually go away once the player mines something or the item updates. Can’t really do anything more about this.

**Comment by JustMztt** [comment]
> The skin does eventually go away once the player mines something or the item updates. Can’t really do anything more about this.

not a big deal then, just wanted to make sure it did go away
